[workspace]
resolver = "2"
members = [
    "crates/rut-core",
    "crates/rut-vm",
    "crates/rut-lexer",
    "crates/rut-ast",
    "crates/rut-parser",
    "crates/rut-lir",
    "crates/rut-driver",
    "crates/rut-wasm",
    "crates/rut-cli",
    "crates/rut-lsp",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
