/**
 * Prepared cases (RFC 0041 §3). Each is self-contained — the host
 * provides the bundled std modules (`std:log`, `std:core`,
 * `std:collection`), whose `info` lines stream back as output.
 * `expected` carries the annotated output lines so the page works in
 * static-preview mode before the wasm build exists. Sources reflect
 * the v1.1 surface: copy-by-value structs, `(T, err)` tuples, no
 * `unit`, no `own`, no `dataclass`, no char literals, no arrows.
 */

export interface RutCase {
  id: string;
  name: string;
  blurb: string;
  /** RFC the case demonstrates */
  rfcs: string;
  source: string;
  expected: string[];
}

export const CASES: RutCase[] = [
  {
    id: "hello-format",
    name: "hello, format",
    blurb: "f-strings, escapes, when on enums",
    rfcs: "0007 §2, 0008",
    source: [
      "import { Logger } from \"std:log\";",
      "",
      "enum Flavor { Sweet, Sour }",
      "",
      "fn describe(f: Flavor) -> str {",
      "    return when (f) {",
      "        Flavor.Sweet -> \"sweet\",",
      "        Flavor.Sour  -> \"sour\",",
      "    };",
      "}",
      "",
      "pub fn main() {",
      "    let log = Logger.new(\"case\");",
      "    let name = \"rut\";",
      "    let n = 41 + 1;",
      "    log.info(f\"hi {name}! n={n} tab:\\t\");",
      "    log.info(describe(Flavor.Sour));",
      "}",
    ].join("\n"),
    expected: [
      "hi rut! n=42 tab:\t",
      "sour",
    ],
  },
  {
    id: "values-and-pointers",
    name: "values & pointers",
    blurb: "copy-by-value bindings, structural ==, sharing via make_ptr",
    rfcs: "0016 §1, 0011 §3, 0005",
    source: [
      "import { Logger } from \"std:log\";",
      "import { make_ptr } from \"std:core\";",
      "",
      "struct Point { x: f32; y: f32; }",
      "",
      "pub fn main() {",
      "    let log = Logger.new(\"case\");",
      "    let mut p = Point { x: 1, y: 2 };",
      "    let q = p;                  // copy-by-value: q owns its own cell",
      "    p.x = 4;                    // q.x is still 1",
      "    let same = Point { x: 1, y: 2 };",
      "    log.info(f\"q.x={q.x} p.x={p.x}\");",
      "    log.info(f\"q==same {q == same}, p==same {p == same}\"); // structural ==",
      "    let rp = make_ptr(p);       // sharing requires a pointer",
      "    rp.x = 9;                   // writes through the pointer (auto-deref)",
      "    log.info(f\"rp.x={rp.x} p.x={p.x}\");              // p keeps 4",
      "    let rq = make_ptr(same);",
      "    log.info(f\"rp==rp {rp == rp}, rp==rq {rp == rq}\"); // pointer identity",
      "}",
    ].join("\n"),
    expected: [
      "q.x=1 p.x=4",
      "q==same true, p==same false",
      "rp.x=9 p.x=4",
      "rp==rp true, rp==rq false",
    ],
  },
  {
    id: "opaque",
    name: "Opaque + downcast",
    blurb: "explicit erasure with checked recovery — downcast returns (T, bool)",
    rfcs: "0014",
    source: [
      "import { Logger } from \"std:log\";",
      "import { Opaque, downcast } from \"std:core\";",
      "",
      "struct Point { x: f32; y: f32; }",
      "",
      "pub fn main() {",
      "    let log = Logger.new(\"case\");",
      "    let box1 = Opaque.new(Point { x: 1, y: 2 });",
      "    let box2 = Opaque.new(\"hello\");",
      "    log.info(f\"box1 is Point: {box1 is Point}\");",
      "    log.info(f\"box2 is Point: {box2 is Point}\");",
      "    let p = downcast<Point>(box1);      // (Point, bool)",
      "    if (p.1) {",
      "        log.info(f\"recovered {p.0.x} {p.0.y}\");",
      "    }",
      "}",
    ].join("\n"),
    expected: [
      "box1 is Point: true",
      "box2 is Point: false",
      "recovered 1 2",
    ],
  },
  {
    id: "sieve",
    name: "sieve",
    blurb: "flat Vec<u8>/Vec<i32> primitive buffers, for loops",
    rfcs: "0016 §4",
    source: [
      "import { Vec } from \"std:collection\";",
      "import { Logger } from \"std:log\";",
      "",
      "fn sieve(limit: i32) -> Vec<i32> {",
      "    let mut marks = Vec<u8>.zeroed(limit + 1);   // 0 = candidate, 1 = crossed",
      "    let primes: Vec<i32> = Vec.new();",
      "    for (let i = 2; i <= limit; i += 1) {",
      "        if (marks[i] == 0) {",
      "            primes.push(i);",
      "            let mut m = i * i;",
      "            while (m <= limit) {",
      "                marks[m] = 1;",
      "                m += i;",
      "            }",
      "        }",
      "    }",
      "    return primes;",
      "}",
      "",
      "pub fn main() {",
      "    let log = Logger.new(\"case\");",
      "    let primes = sieve(100);",
      "    log.info(f\"{primes.len()} primes up to 100, last={primes[primes.len() - 1]}\");",
      "}",
    ].join("\n"),
    expected: [
      "25 primes up to 100, last=97",
    ],
  },
  {
    id: "when-exhaustive",
    name: "when & enums",
    blurb: "exhaustive pattern expressions over simple enums",
    rfcs: "0006, 0008",
    source: [
      "import { Logger } from \"std:log\";",
      "",
      "enum Color { Red, Green, Blue }",
      "",
      "fn mix(a: Color, b: Color) -> str {",
      "    return when (a) {",
      "        Color.Red -> when (b) {",
      "            Color.Red   -> \"red+red\",",
      "            Color.Green -> \"yellow\",",
      "            Color.Blue  -> \"magenta\",",
      "        },",
      "        Color.Green -> \"greenish\",",
      "        Color.Blue  -> \"blueish\",",
      "    };",
      "}",
      "",
      "pub fn main() {",
      "    let log = Logger.new(\"case\");",
      "    log.info(mix(Color.Red, Color.Green));",
      "    log.info(mix(Color.Blue, Color.Blue));",
      "}",
    ].join("\n"),
    expected: [
      "yellow",
      "blueish",
    ],
  },
  {
    id: "tuple-errors",
    name: "errors as tuples",
    blurb: "the (T, err) convention — an empty err string is success",
    rfcs: "0004",
    source: [
      "import { Logger } from \"std:log\";",
      "",
      "// v1.1 error convention: `(T, err)` — an empty err string is success.",
      "fn parse_u8(s: str) -> (i32, str) {",
      "    let n = str_len(s);",
      "    if (n == 0) { return (0, \"empty input\"); }",
      "    let mut v = 0;",
      "    for (let c of s) {",
      "        let d = digit(f\"{c}\");",
      "        if (d < 0) { return (0, f\"not a digit: {c}\"); }",
      "        v = v * 10 + d;",
      "        if (v > 255) { return (0, \"out of range\"); }",
      "    }",
      "    return (v, \"\");",
      "}",
      "",
      "fn str_len(s: str) -> i32 {",
      "    let mut n = 0;",
      "    for (let c of s) { n = n + 1; }",
      "    return n;",
      "}",
      "",
      "fn digit(c: str) -> i32 {",
      "    let digits = \"0123456789\";",
      "    let mut i = 0;",
      "    for (let t of digits) {",
      "        if (f\"{t}\" == c) { return i; }",
      "        i = i + 1;",
      "    }",
      "    return -1;",
      "}",
      "",
      "pub fn main() {",
      "    let log = Logger.new(\"case\");",
      "    let ok = parse_u8(\"247\");",
      "    log.info(f\"ok=({ok.0}, \\\"{ok.1}\\\")\");",
      "    let bad = parse_u8(\"9x2\");",
      "    log.info(f\"bad=({bad.0}, \\\"{bad.1}\\\")\");",
      "    let big = parse_u8(\"300\");",
      "    log.info(f\"big=({big.0}, \\\"{big.1}\\\")\");",
      "}",
    ].join("\n"),
    expected: [
      "ok=(247, \"\")",
      "bad=(0, \"not a digit: x\")",
      "big=(0, \"out of range\")",
    ],
  },
  {
    id: "closures-generics",
    name: "closures & generics",
    blurb: "monomorphized generics, anonymous fns, capture",
    rfcs: "0013",
    source: [
      "import { Vec } from \"std:collection\";",
      "import { Logger } from \"std:log\";",
      "",
      "fn map<T, U>(v: Vec<T>, f: fn(T) -> U) -> Vec<U> {",
      "    let out: Vec<U> = Vec.new();",
      "    for (let x of v) { out.push(f(x)); }",
      "    return out;",
      "}",
      "",
      "pub fn main() {",
      "    let log = Logger.new(\"case\");",
      "    let xs = Vec<i32>.from([1, 2, 3, 4]);",
      "    let k = 10;",
      "    let ys = map<i32, i32>(xs, fn (x: i32) -> i32 { return x * k; });  // captures k",
      "    log.info(f\"{ys[0]} {ys[1]} {ys[2]} {ys[3]}\");",
      "}",
    ].join("\n"),
    expected: [
      "10 20 30 40",
    ],
  },
  {
    id: "fuel-demo",
    name: "fuel demo (infinite loop)",
    blurb: "budgets bite: while(true) hits Trap::OutOfFuel — then resume",
    rfcs: "0040 §2",
    source: [
      "import { Logger } from \"std:log\";",
      "",
      "pub fn main() {",
      "    let log = Logger.new(\"case\");",
      "    let mut i = 0;",
      "    while (true) {",
      "        i += 1;",
      "        if (i % 1000000 == 0) {",
      "            log.info(f\"tick {i}\");",
      "        }",
      "    }",
      "}",
    ].join("\n"),
    expected: [
      "tick 1000000",
      "tick 2000000",
      "tick 3000000",
      "...",
      "Trap::OutOfFuel — the frame is parked; press Resume to add fuel",
    ],
  },
];

export const DEFAULT_BUDGET = { fuel: 10_000_000, heapBytes: 4 * 1024 * 1024 };
